name: Bug Report
description: Create a report to help us improve the normalizer
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: original-text
    attributes:
      label: Original Text
      description: "Please provide the exact Spanish text string that is causing the problem."
      placeholder: "Ej: El Rey Felipe VI se reunió a las 15:00 h."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: "What did you expect the normalized text to be?"
      placeholder: "Ej: El Rey Felipe sexto se reunió a las quince horas."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: "What was the actual output from the normalizer?"
      placeholder: "Ej: El Rey Felipe sexto se reunió a las las quince horas."
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: "What version of Python are you using?"
      placeholder: "e.g., 3.10.4"
    validations:
      required: false
