name: Feature Request
description: Suggest an idea or a new normalization rule for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Thanks for suggesting a new feature! We appreciate your ideas."

  - type: textarea
    id: problem-description
    attributes:
      label: What problem would this feature solve?
      description: "Is there a specific pattern or type of text that the normalizer currently handles poorly or not at all? Please provide examples."
      placeholder: "The normalizer doesn't handle currency symbols written after the number, like '100€'."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe the solution you'd like
      description: "A clear and concise description of what you want to happen. How should the text be transformed?"
      placeholder: "A new rule should detect `(number)€` and transform it to `(number) euros`. For example, '100€' should become '100 euros'."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false
